Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -166,65 +166,76 @@ jobs:
     permissions:
       id-token: write
       contents: read
-  
+    
     steps:
       - uses: actions/checkout@v4
-  
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
+    
+      - name: Print OIDC Claims
+        uses: actions/github-script@v7
         with:
-          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
-          aws-region: ${{ secrets.AWS_REGION }}
+          script: |
+            const jwt = await core.getIDToken('sts.amazonaws.com');
+            const payload = jwt.split('.')[1];
+            console.log(Buffer.from(payload, 'base64url').toString('utf8'));
+            
+    # steps:
+    #   - uses: actions/checkout@v4
   
-      - name: Encode ENV_FILE
-        run: |
-          printf "%s" "${{ secrets.ENV_FILE }}" | base64 -w0 > env.b64
+    #   - name: Configure AWS Credentials
+    #     uses: aws-actions/configure-aws-credentials@v4
+    #     with:
+    #       role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
+    #       aws-region: ${{ secrets.AWS_REGION }}
   
-      - name: Deploy via SSM
-        run: |
-          ENV_B64=$(cat env.b64)
+    #   - name: Encode ENV_FILE
+    #     run: |
+    #       printf "%s" "${{ secrets.ENV_FILE }}" | base64 -w0 > env.b64
   
-          COMMAND_ID=$(aws ssm send-command \
-            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
-            --document-name "AWS-RunShellScript" \
-            --comment "Deploy GameHouse" \
-            --parameters "commands=[
-              \"echo '$ENV_B64' | base64 -d > /home/ssm-user/infra/.env\",
-              \"sudo chown ssm-user:ssm-user /home/ssm-user/infra/.env\",
-              \"sudo -u ssm-user -H bash /home/ssm-user/infra/scripts/deploy.sh\"
-              ]" \
-            --query "Command.CommandId" \
-            --output text)
+    #   - name: Deploy via SSM
+    #     run: |
+    #       ENV_B64=$(cat env.b64)
   
-          echo "Command ID: $COMMAND_ID"
+    #       COMMAND_ID=$(aws ssm send-command \
+    #         --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
+    #         --document-name "AWS-RunShellScript" \
+    #         --comment "Deploy GameHouse" \
+    #         --parameters "commands=[
+    #           \"echo '$ENV_B64' | base64 -d > /home/ssm-user/infra/.env\",
+    #           \"sudo chown ssm-user:ssm-user /home/ssm-user/infra/.env\",
+    #           \"sudo -u ssm-user -H bash /home/ssm-user/infra/scripts/deploy.sh\"
+    #           ]" \
+    #         --query "Command.CommandId" \
+    #         --output text)
   
-          for i in {1..60}; do
-            STATUS=$(aws ssm get-command-invocation \
-              --command-id "$COMMAND_ID" \
-              --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
-              --query "Status" \
-              --output text)
+    #       echo "Command ID: $COMMAND_ID"
   
-            echo "Current Status: $STATUS"
+    #       for i in {1..60}; do
+    #         STATUS=$(aws ssm get-command-invocation \
+    #           --command-id "$COMMAND_ID" \
+    #           --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
+    #           --query "Status" \
+    #           --output text)
   
-            if [ "$STATUS" = "Success" ]; then
-              echo "Deployment succeeded!"
-              break
-            fi
+    #         echo "Current Status: $STATUS"
   
-            if [ "$STATUS" = "Failed" ] || \
-               [ "$STATUS" = "Cancelled" ] || \
-               [ "$STATUS" = "TimedOut" ]; then
+    #         if [ "$STATUS" = "Success" ]; then
+    #           echo "Deployment succeeded!"
+    #           break
+    #         fi
   
-              aws ssm get-command-invocation \
-                --command-id "$COMMAND_ID" \
-                --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
+    #         if [ "$STATUS" = "Failed" ] || \
+    #            [ "$STATUS" = "Cancelled" ] || \
+    #            [ "$STATUS" = "TimedOut" ]; then
   
-              exit 1
-            fi
+    #           aws ssm get-command-invocation \
+    #             --command-id "$COMMAND_ID" \
+    #             --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
   
-            sleep 5
-          done
+    #           exit 1
+    #         fi
+  
+    #         sleep 5
+    #       done
   
           aws ssm get-command-invocation \
             --command-id "$COMMAND_ID" \
